// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenPrintDeploy.Server.Data;

#nullable disable

namespace OpenPrintDeploy.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723022654_AddStableClientDeviceIdentity")]
    partial class AddStableClientDeviceIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ClientActivityEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClientUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterDisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterUncPath")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId", "OccurredAt");

                    b.ToTable("ClientActivities");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ClientDeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceIdentifier")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedMachineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdentifier")
                        .IsUnique();

                    b.HasIndex("NormalizedMachineName");

                    b.ToTable("ClientDevices");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ClientPrinterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastOperation")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUncPath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UncPath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId", "NormalizedUncPath")
                        .IsUnique();

                    b.ToTable("ClientPrinters");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ClientUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignedPrinterCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedPrinterCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastSyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncedPrinterCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "NormalizedUsername")
                        .IsUnique();

                    b.ToTable("ClientUsers");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.PrinterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UncPath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UncPath")
                        .IsUnique();

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.RemovedPrinterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UncPath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UncPath")
                        .IsUnique();

                    b.ToTable("RemovedPrinters");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ZoneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ZoneRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupSid")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("ZoneRules");
                });

            modelBuilder.Entity("PrinterEntityZoneEntity", b =>
                {
                    b.Property<Guid>("PrintersId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZonesId")
                        .HasColumnType("TEXT");

                    b.HasKey("PrintersId", "ZonesId");

                    b.HasIndex("ZonesId");

                    b.ToTable("ZonePrinters", (string)null);
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ClientActivityEntity", b =>
                {
                    b.HasOne("OpenPrintDeploy.Server.Data.Entities.ClientUserEntity", "ClientUser")
                        .WithMany("Activities")
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientUser");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ClientPrinterEntity", b =>
                {
                    b.HasOne("OpenPrintDeploy.Server.Data.Entities.ClientUserEntity", "ClientUser")
                        .WithMany("Printers")
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientUser");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ClientUserEntity", b =>
                {
                    b.HasOne("OpenPrintDeploy.Server.Data.Entities.ClientDeviceEntity", "Device")
                        .WithMany("Users")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ZoneRuleEntity", b =>
                {
                    b.HasOne("OpenPrintDeploy.Server.Data.Entities.ZoneEntity", "Zone")
                        .WithMany("Rules")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("PrinterEntityZoneEntity", b =>
                {
                    b.HasOne("OpenPrintDeploy.Server.Data.Entities.PrinterEntity", null)
                        .WithMany()
                        .HasForeignKey("PrintersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenPrintDeploy.Server.Data.Entities.ZoneEntity", null)
                        .WithMany()
                        .HasForeignKey("ZonesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ClientDeviceEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ClientUserEntity", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Printers");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ZoneEntity", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
