// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenPrintDeploy.Server.Data;

#nullable disable

namespace OpenPrintDeploy.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.PrinterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UncPath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UncPath")
                        .IsUnique();

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ZoneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ZoneRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupSid")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("ZoneRules");
                });

            modelBuilder.Entity("PrinterEntityZoneEntity", b =>
                {
                    b.Property<Guid>("PrintersId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZonesId")
                        .HasColumnType("TEXT");

                    b.HasKey("PrintersId", "ZonesId");

                    b.HasIndex("ZonesId");

                    b.ToTable("ZonePrinters", (string)null);
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ZoneRuleEntity", b =>
                {
                    b.HasOne("OpenPrintDeploy.Server.Data.Entities.ZoneEntity", "Zone")
                        .WithMany("Rules")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("PrinterEntityZoneEntity", b =>
                {
                    b.HasOne("OpenPrintDeploy.Server.Data.Entities.PrinterEntity", null)
                        .WithMany()
                        .HasForeignKey("PrintersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenPrintDeploy.Server.Data.Entities.ZoneEntity", null)
                        .WithMany()
                        .HasForeignKey("ZonesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenPrintDeploy.Server.Data.Entities.ZoneEntity", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
